on:
  push:
    paths:
      - 'test.py'

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read test file
        id: read-test
        run: |
          content=$(cat test.py)
          echo "::set-output name=content::$content"

      - name: OpenAI ChatGPT Action
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.OPENAI_API_KEY }}
          prompt: 'Given the following Python unittest code, please provide a detailed description of the test(s) and their purpose in a markdown format suitable for documentation. Consider including the title, purpose, details, and example code in the description.          '
          input: '${{ steps.read-test.outputs.content }}'
          model: 'gpt-4'
          temperature: 1
          max_tokens: 200

      - name: Append Response to Test File
        run: |
          echo "${{ steps.gpt-response.outputs.response }}" >> README.md
