name: Reusable workflow to check organization standards

on:
  workflow_call:
     inputs:
      github-token:
        required: true
        type: string


jobs:
  validate-name:
    runs-on: ubuntu-latest
    steps:

    - name: Check branch protection
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.SECRET_PAT }}
        script: |
          const { owner, repo } = context.repo;
          try {
            const protection = await github.rest.repos.getBranchProtection({
              owner,
              repo,
              branch: 'main'
            });
          } catch (error) {
            if (error.message.includes("Branch not protected")) {
              core.setFailed("The main branch is not protected, please protect it.");
            } else {
              core.setFailed(`An error occurred: ${error.message}`);
            }
            return;
          }
      if: always() # Run step even if previous steps fail.