on:
  push:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read test file
        id: read-test
        run: |
          content=$(cat tests/test_main.py)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=content::$content"

      - name: OpenAI ChatGPT Action
        id: gpt-response
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.OPENAI_API_KEY }}
          prompt: 'Given the following Python unittest code, please provide a detailed description of the test(s) and their purpose in a markdown format suitable for documentation. Consider including the title, purpose, details, and example code in the description. You response will be automaticly appended to the README.md so it is very important that you send back only the markdown code in your reponse.'
          input: '${{ steps.read-test.outputs.content }}'
          model: 'gpt-4'
          temperature: 1
          max_tokens: 200

      - name: Print Response to Log
        run: |
          echo "Response: ${{ steps.gpt-response.outputs.completion }}"

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: README.md
          write-mode: overwrite
          contents: |
            console.log('${{ steps.gpt-response.outputs.completion }}')

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: chat-gpt-branch
          force: true
          message: 'Overwritten by Github Actions - ${date}'
