on:
  push:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read test file
        id: read-test
        run: |
          echo "FILE_CONTENT=$(cat tests/test_main.py)" >> $GITHUB_ENV


      - name: OpenAI ChatGPT Action
        id: gpt-response
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.OPENAI_API_KEY }}
          prompt: 'Given the following Python unittest code, please provide a detailed description of the test(s) and their purpose in a markdown format suitable for documentation. Consider including the title, purpose, details, and example code in the description.          '
          input: '${{ env.FILE_CONTENT }}'
          model: 'gpt-4'
          temperature: 1
          max_tokens: 200

      - name: Print Response to Log
        run: |
          echo "Response: ${{ steps.gpt-response.outputs.completion }}"

      - name: Append Response to Test File
        run: |
          echo "${{ steps.gpt-response.outputs.completion }}" >> README.md
