name: Check Documentation Files

on: [push, pull_request]

jobs:
  validate-name:
    runs-on: ubuntu-latest
    steps:
    - name: Check repository name
      run: |
        repo_name="${{ github.repository }}"
        lower_repo_name="${repo_name,,}"
        
        if [[ "$repo_name" != "$lower_repo_name" ]]; then
          echo "The repository name '$repo_name' should contain only lowercase letters!" >&2
          exit 1
        elif [[ "$repo_name" == *"__"* ]]; then
          echo "The repository name '$repo_name' should contain dashs ( - ) and not underscores ( _ )" >&2
          exit 1
        fi
      shell: bash
