on:
  push:


jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Read markdown files
        id: read-markdown
        run: |
          content=""
          for f in adr/*.md; do
            content="$content$(cat "$f")\n"
          done
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=content::$content"
      
      - name: OpenAI ChatGPT Action
        id: gpt-response
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.OPENAI_API_KEY }}
          prompt: 'Please translate the following English text to French, preserving all markdown formatting and structure exactly as it is. It is very important to send back only the markdown code as the response will be directly appended to the file:'
          input: ${{ steps.read-markdown.outputs.content }}
          model: 'gpt-4'
          temperature: 1
          max_tokens: 200

      - name: Print Translated Content
        run: |
          echo "Translated Content: ${{ steps.gpt-response.outputs.completion }}"
  
      - name: Append Response to README
        run: |
          echo "${{ steps.gpt-response.outputs.completion }}" >> translated.md

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Checkout Repository and Create New Branch
        run: |
          new_branch="translate-to-french-${GITHUB_SHA::8}"
          git checkout -b $new_branch
          echo "Switched to new branch $new_branch"

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ env.NEW_BRANCH }}
          destination_branch: "main"  # or the branch you want to merge into
          pr_title: "Translate Markdown to French"
          pr_body: "This PR contains a translated markdown file."

      