name: test branch protection workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-org-standards:
    uses: redat97/test-repo/.github/workflows/files-presence-validation.yml@main
    with:
        github-token: ${{ secrets.SECRET_PAT }}